# Generated by Django 4.2.3 on 2023-08-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Project Title')),
                ('description', models.CharField(max_length=254, verbose_name='Project Description')),
                ('image', models.ImageField(upload_to=None, verbose_name='Project Image')),
                ('url_demo', models.URLField(blank=True, verbose_name='Url Demo')),
                ('url_source', models.URLField(blank=True, verbose_name='Url Source')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
