# Generated by Django 4.2.2 on 2023-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tag_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Profile Image')),
                ('cv', models.FileField(upload_to='portfolio/files/', verbose_name='CV File')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
