# Generated by Django 4.2.2 on 2023-09-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_demo',
            field=models.URLField(blank=True, verbose_name='URL Demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_source',
            field=models.URLField(blank=True, verbose_name='URL Source'),
        ),
    ]
