# Generated by Django 4.2.2 on 2023-10-02 23:59

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_url_demo_alter_project_url_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url_demo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url_source',
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=150, verbose_name='Project Title')),
                ('description', models.CharField(max_length=254, verbose_name='Project Description')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Project Image')),
                ('url_demo', models.URLField(blank=True, verbose_name='URL Demo')),
                ('url_source', models.URLField(blank=True, verbose_name='URL Source')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.project')),
                ('tags', models.ManyToManyField(to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Project Translation',
                'db_table': 'portfolio_project_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
    ]
